### PR TITLE
[ar] [linuxscout] Arabic Language Support

### PR DESCRIPTION
**Pull request by TiagoSantos81**
Still to be audited and adapted to new object models but looks good overall.

NOTE: remove dummy/empty java class App.java

### CODE REVIEW

**Comment by TiagoSantos81** [comment]
@linuxscout I would like to add this module to my project if you deem it fit from production. 
I will still have to run checks on the binary files and review the project, but on a superficial level, looks good to me.
If you are Ok with this, please do not sync with my project, or you will mess up your project and I won't be able to merge it anyway (see #16).

**Comment by TiagoSantos81** [comment]
@linuxscout As discussed on https://github.com/TiagoSantos81/languagetool/pull/50#issuecomment-548747668, I am planning to integrate your module in the coming days, and then update the files to make your code compatible with recent changes. If you have any objection, please refer it in the meantime.

**Comment by linuxscout** [comment]
Thank you, me and Sohaib affifi work together.

**Comment by TiagoSantos81** [comment]
> Thank you, me and Sohaib affifi work together.

Thank you for your prompt reply. I imagined so, but I prefered to check with you. I will integrate it as soon as possible. 

Best regards.

**Pull request merged**
