### PR TITLE
[ga] Fix message, add some generic rules

### PR DESCRIPTION
**Pull request by jimregan**

### CODE REVIEW

**Comment by TiagoSantos81** [comment]
@jimregan 

Merged with thanks. I have also seen the Irish morphological and spelling dictionary project you have. 
They look great and should be included but I need to think more thoroughly on the repercussions of license change, although, so far with my limited understanding of it, I have nothing against it. 

Regarding the speller, is it possible to integrate temporarily a lower quality alternatives - doesn't matter if it is Hunspell or Morphologic - with compatible license? I made a quick search and I have only found Gaelspell, which would lead to me thinking about the license topic that I don't want to think right now.

Best regards

**Comment by TiagoSantos81** [comment]
@jimregan It would also be nice to add links to your projects, so users can find those dictionaries and get to know your work.

**Comment by jimregan** [comment]
That the dictionaries are GPL-licensed shouldn't be a problem: there's nothing that's being 'linked' (their inclusion in no way creates a derivative work). Putting them in a jar the way it had been done just gave an easy location for the resource loader to find them.

**Comment by TiagoSantos81** [comment]
@jimregan I have notice that, later on reading about licence linkability and the info in languagetool /third-party-licenses/. I have integrated them in this repo.
Of interest to you may be the recent commits to `ga/grammar.xml` and the info files. They add example and remove most warnings from the testrules tests, to help further develop the rules, should you wish to do it. Some tweaks to the speller behaviour were also done.
Tomorrow, I will push a machine translation of the MessageBundle, so there is some sort of localization for Irish.

**Pull request merged**
