### PR TITLE
[WIP] [ga] Jim Regan Irish grammar

### PR DESCRIPTION
**Pull request by TiagoSantos81**

### CODE REVIEW

**Comment by TiagoSantos81** [comment]
@jimregan I plan to integrate this on my project and update the code to make it work with the changes that occurred in the meantime. Any objection?

**Comment by jimregan** [comment]
Sure, go ahead. I even tried to fix a merge conflict here, but something weird happened

**Comment by TiagoSantos81** [comment]
@jimregan Great thanks. There were some changes to language definition and that may have caused you trouble. I will see what I can do and update you when it is done. 
Best regards.

**Comment by TiagoSantos81** [comment]
Closed due to date attempt sync. Another merge will be done.

**Comment by TiagoSantos81** [comment]
@jimregan 
Just for the sake of this merge, can you reset your HEAD to commit 6fb0251 and not reapply merges? 
Might be easier to revert temporarily to `aa71ffd`, so my changes on this branch are not overwritten.
It just a `git revert aa71ffd`, I do the simple merge pull request that keeps your contributions on my log, and when we are done with this, you revert that again. I won't add other commits to the mix in the meantime.

I am in a middle of a branch experiment trying to detach the head of a checkout from your repo, but this is really tricky I easy to mess up and have to restart all over again.

**Comment by TiagoSantos81** [comment]
Closed with bc2c4e5

**Pull request closed without merging**
